/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2026 Ivan Ivanets
 */

#include "adapter.h"

#include "registrations/profile_v1.h"

#include <acvp/acvp.h>
#include <ngi541/engine.h>

#include <stdio.h>
#include <stdlib.h>

int
ngi541_acvp_adapter_build_probe (void)
{
  ACVP_CTX *acvp_ctx = NULL;
  ACVP_RESULT result;
  ngi541_status_t status;

  status = ngi541_engine_init ();

  if (status != NGI541_STATUS_OK)
    return 1;

  result =
    acvp_create_test_session (
      &acvp_ctx,
      NULL,
      ACVP_LOG_LVL_INFO);

  if (result != ACVP_SUCCESS)
    return 2;

  result =
    ngi541_acvp_register_profile_v1 (
      acvp_ctx);

  if (result != ACVP_SUCCESS)
    {
      acvp_free_test_session (acvp_ctx);
      return 3;
    }

  result =
    acvp_free_test_session (
      acvp_ctx);

  if (result != ACVP_SUCCESS)
    return 4;

  return 0;
}

int
ngi541_acvp_print_registration (void)
{
  ACVP_CTX *acvp_ctx = NULL;
  ACVP_RESULT result;
  ACVP_RESULT free_result;
  char *registration;

  /*
   * Registration introspection does not execute NGI541 crypto
   * operations. It only asks libacvp to serialize the currently
   * registered profile.
   *
   * Do not initialize the NGI541 execution engine here: this path
   * is intentionally limited to capability/profile introspection.
   */
  result =
    acvp_create_test_session (
      &acvp_ctx,
      NULL,
      ACVP_LOG_LVL_INFO);

  if (result != ACVP_SUCCESS)
    return 1;

  result =
    ngi541_acvp_register_profile_v1 (
      acvp_ctx);

  if (result != ACVP_SUCCESS)
    {
      acvp_free_test_session (acvp_ctx);
      return 2;
    }

  /*
   * This is the registration JSON generated by libacvp itself from
   * the capabilities registered above. The returned string is owned
   * by the caller and must be freed.
   */
  registration =
    acvp_get_current_registration (
      acvp_ctx,
      NULL);

  if (registration == NULL)
    {
      acvp_free_test_session (acvp_ctx);
      return 3;
    }

  /*
   * stdout is deliberately reserved for the JSON payload so that:
   *
   *   ngi541_acvp --registration | jq .
   *
   * can be used directly by CI and audit tooling.
   */
  if (printf ("%s\n", registration) < 0)
    {
      free (registration);
      acvp_free_test_session (acvp_ctx);
      return 4;
    }

  free (registration);

  free_result =
    acvp_free_test_session (
      acvp_ctx);

  if (free_result != ACVP_SUCCESS)
    return 5;

  return 0;
}

int
ngi541_acvp_run_offline (
  const char *request_filename,
  const char *response_filename)
{
  ACVP_CTX *acvp_ctx = NULL;
  ACVP_RESULT result;
  ACVP_RESULT free_result;
  ngi541_status_t status;

  if (request_filename == NULL ||
      response_filename == NULL)
    return 1;

  status =
    ngi541_engine_init ();

  if (status != NGI541_STATUS_OK)
    return 2;

  result =
    acvp_create_test_session (
      &acvp_ctx,
      NULL,
      ACVP_LOG_LVL_INFO);

  if (result != ACVP_SUCCESS)
    return 3;

  result =
    ngi541_acvp_register_profile_v1 (
      acvp_ctx);

  if (result != ACVP_SUCCESS)
    {
      acvp_free_test_session (acvp_ctx);
      return 4;
    }

  /*
   * Parse the offline ACVP request, dispatch each test case
   * through the registered NGI541 callbacks, and serialize
   * the response JSON.
   */
  result =
    acvp_run_vectors_from_file_offline (
      acvp_ctx,
      request_filename,
      response_filename);

  free_result =
    acvp_free_test_session (
      acvp_ctx);

  if (result != ACVP_SUCCESS)
    return 5;

  if (free_result != ACVP_SUCCESS)
    return 6;

  return 0;
}