/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2026 Ivan Ivanets
 */

#include "adapter.h"

#include <stdio.h>
#include <string.h>

int
main (
  int argc,
  char **argv)
{
  int result;

  /*
   * Preserve the original build/registration probe.
   */
  if (argc == 1)
    return ngi541_acvp_adapter_build_probe ();

  /*
   * Print the exact registration JSON generated by libacvp
   * from the currently selected NGI541 ACVP profile.
   *
   * stdout contains JSON only; diagnostics go to stderr.
   */
  if (argc == 2 &&
      strcmp (argv[1], "--registration") == 0)
    {
      result =
        ngi541_acvp_print_registration ();

      if (result != 0)
        {
          fprintf (
            stderr,
            "NGI541 ACVP registration generation failed: %d\n",
            result);

          return result;
        }

      return 0;
    }

  /*
   * Offline vector processing:
   *
   *   ngi541_acvp request.json response.json
   */
  if (argc != 3)
    {
      fprintf (
        stderr,
        "usage:\n"
        "  %s\n"
        "  %s --registration\n"
        "  %s request.json response.json\n",
        argv[0],
        argv[0],
        argv[0]);

      return 64;
    }

  result =
    ngi541_acvp_run_offline (
      argv[1],
      argv[2]);

  if (result != 0)
    {
      fprintf (
        stderr,
        "NGI541 ACVP offline processing failed: %d\n",
        result);

      return result;
    }

  return 0;
}